// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/chatservice.proto

#ifndef GRPC_MOCK_proto_2fchatservice_2eproto__INCLUDED
#define GRPC_MOCK_proto_2fchatservice_2eproto__INCLUDED

#include "proto/chatservice.pb.h"
#include "proto/chatservice.grpc.pb.h"

#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/sync_stream.h>
#include <gmock/gmock.h>
namespace chat {

class MockChatServiceStub : public ChatService::StubInterface {
 public:
  MOCK_METHOD3(Send, ::grpc::Status(::grpc::ClientContext* context, const ::chat::ChatMessage& request, ::chat::Response* response));
  MOCK_METHOD3(AsyncSendRaw, ::grpc::ClientAsyncResponseReaderInterface< ::chat::Response>*(::grpc::ClientContext* context, const ::chat::ChatMessage& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncSendRaw, ::grpc::ClientAsyncResponseReaderInterface< ::chat::Response>*(::grpc::ClientContext* context, const ::chat::ChatMessage& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD2(ReadChatRaw, ::grpc::ClientReaderInterface< ::chat::ChatMessage>*(::grpc::ClientContext* context, const ::chat::ChatReader& request));
  MOCK_METHOD4(AsyncReadChatRaw, ::grpc::ClientAsyncReaderInterface< ::chat::ChatMessage>*(::grpc::ClientContext* context, const ::chat::ChatReader& request, ::grpc::CompletionQueue* cq, void* tag));
  MOCK_METHOD3(PrepareAsyncReadChatRaw, ::grpc::ClientAsyncReaderInterface< ::chat::ChatMessage>*(::grpc::ClientContext* context, const ::chat::ChatReader& request, ::grpc::CompletionQueue* cq));
};

}  // namespace chat


#endif  // GRPC_MOCK_proto_2fchatservice_2eproto__INCLUDED
