// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/chatservice.proto

#include "proto/chatservice.pb.h"
#include "proto/chatservice.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace chat {

static const char* ChatService_method_names[] = {
  "/chat.ChatService/Send",
  "/chat.ChatService/ReadChat",
};

std::unique_ptr< ChatService::Stub> ChatService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ChatService::Stub> stub(new ChatService::Stub(channel, options));
  return stub;
}

ChatService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Send_(ChatService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReadChat_(ChatService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::Status ChatService::Stub::Send(::grpc::ClientContext* context, const ::chat::ChatMessage& request, ::chat::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::chat::ChatMessage, ::chat::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Send_, context, request, response);
}

void ChatService::Stub::async::Send(::grpc::ClientContext* context, const ::chat::ChatMessage* request, ::chat::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::chat::ChatMessage, ::chat::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Send_, context, request, response, std::move(f));
}

void ChatService::Stub::async::Send(::grpc::ClientContext* context, const ::chat::ChatMessage* request, ::chat::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Send_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::chat::Response>* ChatService::Stub::PrepareAsyncSendRaw(::grpc::ClientContext* context, const ::chat::ChatMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::chat::Response, ::chat::ChatMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Send_, context, request);
}

::grpc::ClientAsyncResponseReader< ::chat::Response>* ChatService::Stub::AsyncSendRaw(::grpc::ClientContext* context, const ::chat::ChatMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::chat::ChatMessage>* ChatService::Stub::ReadChatRaw(::grpc::ClientContext* context, const ::chat::ChatReader& request) {
  return ::grpc::internal::ClientReaderFactory< ::chat::ChatMessage>::Create(channel_.get(), rpcmethod_ReadChat_, context, request);
}

void ChatService::Stub::async::ReadChat(::grpc::ClientContext* context, const ::chat::ChatReader* request, ::grpc::ClientReadReactor< ::chat::ChatMessage>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::chat::ChatMessage>::Create(stub_->channel_.get(), stub_->rpcmethod_ReadChat_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::chat::ChatMessage>* ChatService::Stub::AsyncReadChatRaw(::grpc::ClientContext* context, const ::chat::ChatReader& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::chat::ChatMessage>::Create(channel_.get(), cq, rpcmethod_ReadChat_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::chat::ChatMessage>* ChatService::Stub::PrepareAsyncReadChatRaw(::grpc::ClientContext* context, const ::chat::ChatReader& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::chat::ChatMessage>::Create(channel_.get(), cq, rpcmethod_ReadChat_, context, request, false, nullptr);
}

ChatService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatService::Service, ::chat::ChatMessage, ::chat::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chat::ChatMessage* req,
             ::chat::Response* resp) {
               return service->Send(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatService_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< ChatService::Service, ::chat::ChatReader, ::chat::ChatMessage>(
          [](ChatService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::chat::ChatReader* req,
             ::grpc::ServerWriter<::chat::ChatMessage>* writer) {
               return service->ReadChat(ctx, req, writer);
             }, this)));
}

ChatService::Service::~Service() {
}

::grpc::Status ChatService::Service::Send(::grpc::ServerContext* context, const ::chat::ChatMessage* request, ::chat::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatService::Service::ReadChat(::grpc::ServerContext* context, const ::chat::ChatReader* request, ::grpc::ServerWriter< ::chat::ChatMessage>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace chat

